#!/bin/bash

## Copyright ©UDPTeam

## Discord: [URL]https://discord.gg/civ3[/URL]

## Script to keep-alive your DNSTT server domain record query from target resolver/local DNS server

## Run this script excluded from your VPN tunnel (split VPN tunneling mode)

## Run command: ./globe-james.sh l

## Repeat dig command loop time (seconds) (positive integer only)

LOOP_DELAY=1  # Set the loop delay to 1 second

## Your DNSTT Nameserver & your Domain `A` Record

NS='ns-ph5.vpnjz.com'
NS1='dns.ssh-sg-3.vpnsvr.net'
NS2='dns.xs-1.optnl.com'
A='ns-ph5.vpnjz.com'

## Add your DNS here

declare -a HOSTS=('121.54.70.134' '124.6.181.12' '124.6.181.36' '124.6.181.20')

## Linux' dig command executable filepath
## Select value: "CUSTOM|C" or "DEFAULT|D"

DIG_EXEC="DEFAULT"

## if set to CUSTOM, enter your custom dig executable path here

CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig

######################################
######################################
######################################
######################################
######################################

VER=0.1

# Define text color codes
PINK='\e[32m'
ORANGE='\e[31m'
RESET='\e[0m'

case "${DIG_EXEC}" in
DEFAULT|D)
    _DIG="$(command -v dig)"
    ;;
CUSTOM|C)
    _DIG="${CUSTOM_DIG}"
    ;;
esac

if [ ! $(command -v ${_DIG}) ]; then
    printf "Dig command failed to run, please install dig (dnsutils) or check DIG_EXEC & CUSTOM_DIG variables inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n"
    exit 1
fi

# Function to check DNS resolution and ping DNS nameservers
check() {
    for host in "${HOSTS[@]}"; do
        (timeout -k 3 3 ${_DIG} @"$host" "$A" && echo -e "${GREEN}Host $host: DNS resolution successful.${RESET}") || echo -e "${RED}Host $host: DNS resolution failed.${RESET}"
    done

    # Add DNS nameservers and host IPs to check with ping
    PING_TARGETS=("$NS" "$NS1" "${HOSTS[@]}")

    for target in "${PING_TARGETS[@]}"; do
        if ping -c 1 -W 2 "$target" &>/dev/null; then
            echo -e "${PINK}Ping to $target: Success.${RESET}"
        else
            echo -e "${ORANGE}Ping to $target: Failed.${RESET}"
        fi
    done
}

echo "DNSTT Keep-Alive script with DNS and host IP ping<Discord @civ3>"
echo "DNS List: ${HOSTS[*]}"
echo "CTRL + C to close script"

while true; do
    check
    echo '.JAMES_BLU'
    sleep ${LOOP_DELAY}
done
